name: Publish Release Docker

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build Docker & Upload Assets
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d8c007052462b96d19282751
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/daylog

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Update TAG_NAME in .env.example
        run: |
          RELEASE_TAG=${{ github.event.release.tag_name }}
          
          if grep -q "TAG_NAME=" .env.example; then
            sed -i "s|TAG_NAME=.*|TAG_NAME=$RELEASE_TAG|g" .env.example
          else
            echo -e "\nTAG_NAME=$RELEASE_TAG" >> .env.example
          fi
          
          echo "âœ… .env.example updated: TAG_NAME=$RELEASE_TAG"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@c95fe1489396fe8a2169f11b973b987624c26a67
        with:
          files: |
            docker-compose.yml
            .env.example
